runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css
  static_dir: static/css
- url: /static/js
  static_dir: static/js
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
